export type Drink = {
  name: string;
  type: string;
  alcohol: number;
  taste: string;
  region: string;
  pairing: string;
  image: string;
  description: string;
  mood: string;
  year: number;
};

export const drinks: Drink[] = [
  {
    name: "アサヒ スーパードライ",
    type: "ビール",
    alcohol: 5,
    taste: "キレのある辛口",
    region: "東京都",
    pairing: "唐揚げ、餃子",
    image:
      "https://m.media-amazon.com/images/I/812T0aaN0NL._UF1000,1000_QL80_.jpg",
    description: "定番の国産ビール。スッキリ爽快。",
    mood: "仕事終わりのリフレッシュ",
    year: 2023,
  },
  {
    name: "キリン 一番搾り",
    type: "ビール",
    alcohol: 5,
    taste: "まろやかでバランスが良い",
    region: "神奈川県",
    pairing: "焼き鳥、枝豆",
    image: "https://www.miraido-onlineshop.com/images/cat/krnbericbnsbnm-2.jpg",
    description: "優しいコクと飲みやすさが魅力。",
    mood: "ほっとリラックスしたいとき",
    year: 2022,
  },
  {
    name: "サッポロ 黒ラベル",
    type: "ビール",
    alcohol: 5,
    taste: "深いコクと香り",
    region: "北海道",
    pairing: "ステーキ、焼き魚",
    image: "https://m.media-amazon.com/images/I/515e-u1BhGL.jpg",
    description: "黒ビールの王道。濃厚な味わい。",
    mood: "特別な日の乾杯に",
    year: 2021,
  },
  {
    name: "レモンサワー",
    type: "サワー",
    alcohol: 5,
    taste: "さっぱり・爽快",
    region: "日本全国",
    pairing: "唐揚げ、焼き鳥",
    image:
      "https://setouchi-lemon.jp/wp-content/uploads/2020/10/%E3%83%AC%E3%83%A2%E3%83%B3%E3%82%B5%E3%83%AF%E3%83%BC%EF%BC%93.jpeg",
    description: "シンプルで爽快な味わい、居酒屋の定番。",
    mood: "リフレッシュしたい時",
    year: 2023,
  },
  {
    name: "グレープフルーツサワー",
    type: "サワー",
    alcohol: 5,
    taste: "爽やかでほろ苦い",
    region: "日本全国",
    pairing: "サラダ、魚介",
    image: "https://grafrufes.com/wp-content/uploads/2019/04/02.jpg",
    description: "果実感たっぷりでスッキリとした後味。",
    mood: "軽く飲みたい時",
    year: 2023,
  },
  {
    name: "カルピスサワー",
    type: "サワー",
    alcohol: 5,
    taste: "甘酸っぱい・まろやか",
    region: "日本全国",
    pairing: "揚げ物、スパイシー料理",
    image:
      "https://www.asahibeer.co.jp/cocktail/search/image/item/2000000083.jpg",
    description: "カルピスの優しい甘さと酸味がクセになる。",
    mood: "甘い気分の時",
    year: 2023,
  },
  {
    name: "赤ワイン",
    type: "ワイン",
    alcohol: 12,
    taste: "渋みと果実味",
    region: "フランス/チリ/日本など",
    pairing: "肉料理、チーズ",
    image:
      "https://www.ozmall.co.jp/Content/upload/images/ZJL3KYH7Q35OZHNSIWSCGXECEA.jpg",
    description: "芳醇な香りと奥深い味わいを楽しめるワイン。",
    mood: "落ち着いて語りたい夜に",
    year: 2019,
  },
  {
    name: "カシスオレンジ",
    type: "カクテル",
    alcohol: 8,
    taste: "甘酸っぱい・フルーティ",
    region: "世界中のバー",
    pairing: "デザート、軽食",
    image:
      "https://www.olive-hitomawashi.com/column/assets_c/2020/03/AdobeStock_268259179-thumb-500xauto-288375.jpg",
    description: "カシスリキュールとオレンジジュースの定番カクテル。",
    mood: "女子会や初めてのお酒に",
    year: 2023,
  },
  {
    name: "ウーロンハイ",
    type: "チューハイ",
    alcohol: 7,
    taste: "すっきり、ほろ苦い",
    region: "日本",
    pairing: "唐揚げ、焼き鳥",
    image:
      "https://agf.ajinomoto.co.jp/agfprofessional/images/recipe/recipeimg_oolonghigh_sp.jpg",
    description: "ウーロン茶と焼酎の組み合わせで飲みやすく仕上げた一杯。",
    mood: "仕事帰りにさっと一杯",
    year: 2025,
  },
  {
    name: "緑茶ハイ",
    type: "チューハイ",
    alcohol: 7,
    taste: "さっぱり、ほのかな苦み",
    region: "日本",
    pairing: "和食、揚げ物",
    image:
      "https://agf.ajinomoto.co.jp/agfprofessional/images/recipe/recipeimg_greenteahigh_sp.jpg",
    description: "緑茶の香りと焼酎が爽やかに調和した飲みやすいカクテル。",
    mood: "ほっと一息つきたい時に",
    year: 2025,
  },
  {
    name: "カシスウーロン",
    type: "カクテル",
    alcohol: 8,
    taste: "甘酸っぱい、フルーティー",
    region: "日本",
    pairing: "デザート、フルーツ系料理",
    image:
      "https://cdn.macaro-ni.jp/assets/img/shutterstock/shutterstock_154600424.jpg",
    description: "カシスの甘みとウーロン茶の渋みが絶妙にマッチ。",
    mood: "友達とゆったり話す夜に",
    year: 2025,
  },
  {
    name: "ファジーネーブル",
    type: "カクテル",
    alcohol: 7,
    taste: "甘くフルーティー",
    region: "アメリカ",
    pairing: "軽食、スナック",
    image:
      "https://bonaccord.jp/wp-content/uploads/2022/07/%E3%83%95%E3%82%A1%E3%82%B8%E3%83%BC%E3%83%8D%E3%83%BC%E3%83%96%E3%83%AB-scaled.jpeg",
    description: "ピーチリキュールとオレンジジュースで作る華やかなカクテル。",
    mood: "明るく楽しいパーティーに",
    year: 2025,
  },
  {
    name: "モスコミュール",
    type: "カクテル",
    alcohol: 10,
    taste: "ジンジャーの辛味とライムの酸味",
    region: "アメリカ",
    pairing: "ピザ、揚げ物",
    image:
      "https://bonaccord.jp/wp-content/uploads/2022/07/cocktail-gc08e60864_1920.jpg",
    description:
      "ジン、ジンジャービア、ライムを使った爽やかでキリッとしたカクテル。",
    mood: "リフレッシュしたい時に",
    year: 2025,
  },
  {
    name: "ジントニック",
    type: "カクテル",
    alcohol: 10,
    taste: "爽快、やや苦味",
    region: "イギリス",
    pairing: "シーフード、サラダ",
    image:
      "https://mi-journey.jp/foodie/wp-content/uploads/2024/03/240208gin11.jpg",
    description: "ジンとトニックウォーターのシンプルで爽やかな一杯。",
    mood: "涼しい夜に軽く飲みたい時",
    year: 2025,
  },
  {
    name: "スクリュードライバー",
    type: "カクテル",
    alcohol: 9,
    taste: "甘酸っぱい、フルーティー",
    region: "アメリカ",
    pairing: "軽食、サンドイッチ",
    image: "https://cocktailrecipe.jp/img/card/screwDriver.WebP",
    description: "ウォッカとオレンジジュースを合わせたシンプルなカクテル。",
    mood: "昼間や休日に気軽に楽しみたい時",
    year: 2025,
  },
  {
    name: "テキーラサンライズ",
    type: "カクテル",
    alcohol: 12,
    taste: "甘酸っぱい、爽やか",
    region: "メキシコ",
    pairing: "チキン料理、タコス",
    image:
      "https://www.asahibeer.co.jp/cocktail/search/image/item/1010400429.jpg",
    description:
      "テキーラにオレンジジュースとグレナデンを加え、見た目も華やかなカクテル。",
    mood: "朝や昼のイベントにぴったり",
    year: 2025,
  },
  {
    name: "コークハイ",
    type: "ハイボール",
    alcohol: 9,
    taste: "甘くコクがある",
    region: "日本",
    pairing: "揚げ物、焼き鳥",
    image: "https://cocktailrecipe.jp/img/card/coke_highball.WebP",
    description: "ウイスキーとコーラを合わせた定番のハイボール。",
    mood: "居酒屋でゆったり飲む夜に",
    year: 2025,
  },
  {
    name: "ジンジャーハイボール",
    type: "ハイボール",
    alcohol: 9,
    taste: "スパイシーで爽快",
    region: "日本",
    pairing: "肉料理、餃子",
    image: "https://image.tanoshiiosake.jp/images/28395.jpg",
    description:
      "ウイスキーとジンジャーエールのスパイシーで飲みやすい組み合わせ。",
    mood: "ちょっとピリッとした刺激が欲しい時に",
    year: 2025,
  },
  {
    name: "レッドアイ",
    type: "カクテル",
    alcohol: 5,
    taste: "ビールの苦味とトマトの旨味",
    region: "アメリカ",
    pairing: "朝食、軽食",
    image:
      "https://inageya-yell.com/wp-content/uploads/2023/09/pc_sec3_ttl_img-3-e1695270465820.png",
    description:
      "ビールとトマトジュースを混ぜた、さっぱりした飲みやすいカクテル。",
    mood: "朝や昼に軽く楽しみたい時",
    year: 2025,
  },
  {
    name: "白ワイン",
    type: "ワイン",
    alcohol: 11,
    taste: "酸味と果実味",
    region: "フランス/チリ/日本など",
    pairing: "魚料理、サラダ",
    image:
      "https://www.biccamera.com/bc/include_cms_contents/topics/osusume_white_wine/01.jpg",
    description: "フルーティーで軽やかな香りを楽しめるワイン。",
    mood: "さっぱりとした気分で語りたい夜に",
    year: 2019,
  },
  {
    name: "白鹿 純米酒",
    type: "日本酒",
    alcohol: 15,
    taste: "米の旨味とキレ",
    region: "関西",
    pairing: "刺身、天ぷら",
    image:
      "https://www.hakushika.co.jp/wp-content/uploads/2020/01/junmai_1.8.jpg",
    description: "米の旨味が広がる食中に合う定番純米。",
    mood: "落ち着いて語りたい夜に",
    year: 2021,
  },
  {
    name: "獺祭 純米大吟醸",
    type: "日本酒",
    alcohol: 16,
    taste: "フルーティーで上品",
    region: "日本",
    pairing: "白身魚、チーズ",
    image: "https://www.asahishuzo.ne.jp/products/img/45_720.jpg",
    description: "華やかな香りと繊細な甘みの人気銘柄。",
    mood: "特別な日の乾杯に",
    year: 2024,
  },
  {
    name: "黒霧島",
    type: "焼酎",
    alcohol: 25,
    taste: "コクがある、甘い香り",
    region: "九州",
    pairing: "焼き鳥、唐揚げ",
    image: "https://image.tanoshiiosake.jp/images/24521.jpg",
    description: "芋の甘い香りとすっきりとした後味の定番芋焼酎。",
    mood: "ゆったり家飲みに",
    year: 2020,
  },
  {
    name: "二階堂",
    type: "焼酎",
    alcohol: 25,
    taste: "まろやかで飲みやすい",
    region: "九州",
    pairing: "和食全般",
    image: "https://image.tanoshiiosake.jp/images/24985.jpg",
    description: "麦の香りがやさしく広がる麦焼酎。",
    mood: "リラックスしたい時",
    year: 2019,
  },
  {
    name: "白州 ハイボール",
    type: "ハイボール",
    alcohol: 9,
    taste: "さっぱり、森林香",
    region: "日本",
    pairing: "サラダ、チキン",
    image: "https://www.suntory.co.jp/whisky/hakushu/common/img/kv_sp.jpg",
    description: "爽やかな香りが特徴の上質ハイボール。",
    mood: "涼しい夜に軽く飲みたい時",
    year: 2024,
  },
  {
    name: "バーボンハイボール",
    type: "ハイボール",
    alcohol: 10,
    taste: "甘くコクがある",
    region: "アメリカ",
    pairing: "バーガー、ステーキ",
    image: "https://cocktailrecipe.jp/img/card/bourbon_highball.WebP",
    description: "バニラ香の余韻が心地よいハイボール。",
    mood: "パーティー",
    year: 2023,
  },
  {
    name: "梅酒ロック",
    type: "リキュール",
    alcohol: 12,
    taste: "甘酸っぱい",
    region: "日本",
    pairing: "デザート、チーズ",
    image: "https://image.tanoshiiosake.jp/images/27405.jpg",
    description: "とろりとした甘酸っぱさで飲みやすい。",
    mood: "甘い気分の時",
    year: 2022,
  },
  {
    name: "ネグローニ",
    type: "カクテル",
    alcohol: 24,
    taste: "ビターで香草香",
    region: "イタリア",
    pairing: "生ハム、チーズ",
    image: "https://www.hakushu-online.jp/assets/img/recipes/negroni.jpg",
    description: "ジン、ベルモット、カンパリの大人のビター。",
    mood: "語りたい夜",
    year: 2025,
  },
  {
    name: "アペロールスプリッツ",
    type: "カクテル",
    alcohol: 11,
    taste: "爽やか、ほろ苦い",
    region: "イタリア",
    pairing: "前菜、サラダ",
    image:
      "https://www.campari.com/jp-ja/wp-content/uploads/sites/6/2020/06/aperol-spritz.jpg",
    description: "軽やかなビターオレンジの食前酒カクテル。",
    mood: "休日昼間",
    year: 2025,
  },
  {
    name: "マルガリータ",
    type: "カクテル",
    alcohol: 18,
    taste: "酸味と塩味、爽快",
    region: "メキシコ",
    pairing: "タコス、ナチョス",
    image: "https://cocktailrecipe.jp/img/card/margarita.WebP",
    description: "テキーラとライムの王道。",
    mood: "パーティー",
    year: 2025,
  },
  {
    name: "白桃サワー",
    type: "サワー",
    alcohol: 5,
    taste: "甘くフルーティー",
    region: "日本全国",
    pairing: "サラダ、デザート",
    image: "https://image.tanoshiiosake.jp/images/30675.jpg",
    description: "みずみずしい桃の香りが広がるサワー。",
    mood: "女子会や初めてのお酒に",
    year: 2024,
  },
  {
    name: "ゆずサワー",
    type: "サワー",
    alcohol: 5,
    taste: "さっぱり、柑橘香",
    region: "日本全国",
    pairing: "唐揚げ、焼き鳥",
    image: "https://image.tanoshiiosake.jp/images/30688.jpg",
    description: "爽やかな柚子の香りで食事に合う。",
    mood: "リフレッシュしたい時",
    year: 2024,
  },
  {
    name: "IPA クラフトビール",
    type: "ビール",
    alcohol: 6.5,
    taste: "ホップの苦味と香り",
    region: "関東",
    pairing: "ピザ、バーガー",
    image: "https://image.tanoshiiosake.jp/images/31638.jpg",
    description: "トロピカルな香りと力強い苦味のIPA。",
    mood: "特別な日の乾杯に",
    year: 2025,
  },
  {
    name: "ヘーフェヴァイツェン",
    type: "ビール",
    alcohol: 5.5,
    taste: "バナナ香、まろやか",
    region: "海外",
    pairing: "ソーセージ、サラダ",
    image: "https://image.tanoshiiosake.jp/images/31637.jpg",
    description: "小麦由来の柔らかな口当たりと香り。",
    mood: "休日昼間",
    year: 2023,
  },
  {
    name: "スパークリングワイン",
    type: "ワイン",
    alcohol: 12,
    taste: "爽やかでキレ",
    region: "フランス/日本など",
    pairing: "前菜、魚介",
    image: "https://www.biccamera.com/bc/itemimg/00000008393122_A01.jpg",
    description: "きめ細かな泡が食事を引き立てる。",
    mood: "特別な日の乾杯に",
    year: 2022,
  },
];
