export type Drink = {
  name: string;
  type: string;
  alcohol: number;
  taste: string;
  region: string;
  pairing: string;
  image: string;
  description: string;
  mood: string;
  year: number;
};

export const drinks: Drink[] = [
  {
    name: "アサヒ スーパードライ",
    type: "ビール",
    alcohol: 5,
    taste: "キレのある辛口",
    region: "東京都",
    pairing: "唐揚げ、餃子",
    image: "/images/noimage.png", // ローカル画像
    description: "定番の国産ビール。スッキリ爽快。",
    mood: "仕事終わりのリフレッシュ",
    year: 2023,
  },
  {
    name: "キリン 一番搾り",
    type: "ビール",
    alcohol: 5,
    taste: "まろやかでバランスが良い",
    region: "神奈川県",
    pairing: "焼き鳥、枝豆",
    image: "/images/noimage.png",
    description: "優しいコクと飲みやすさが魅力。",
    mood: "ほっとリラックスしたいとき",
    year: 2022,
  },
  {
    name: "サッポロ 黒ラベル",
    type: "ビール",
    alcohol: 5,
    taste: "深いコクと香り",
    region: "北海道",
    pairing: "ステーキ、焼き魚",
    image: "/images/noimage.png",
    description: "黒ビールの王道。濃厚な味わい。",
    mood: "特別な日の乾杯に",
    year: 2021,
  },
  {
    name: "レモンサワー",
    type: "サワー",
    alcohol: 5,
    taste: "さっぱり・爽快",
    region: "日本全国",
    pairing: "唐揚げ、焼き鳥",
    image: "/images/noimage.png",
    description: "シンプルで爽快な味わい、居酒屋の定番。",
    mood: "リフレッシュしたい時",
    year: 2023,
  },
  {
    name: "グレープフルーツサワー",
    type: "サワー",
    alcohol: 5,
    taste: "爽やかでほろ苦い",
    region: "日本全国",
    pairing: "サラダ、魚介",
    image: "/images/noimage.png",
    description: "果実感たっぷりでスッキリとした後味。",
    mood: "軽く飲みたい時",
    year: 2023,
  },
  {
    name: "カルピスサワー",
    type: "サワー",
    alcohol: 5,
    taste: "甘酸っぱい・まろやか",
    region: "日本全国",
    pairing: "揚げ物、スパイシー料理",
    image: "/images/noimage.png",
    description: "カルピスの優しい甘さと酸味がクセになる。",
    mood: "甘い気分の時",
    year: 2023,
  },
  {
    name: "白桃サワー",
    type: "サワー",
    alcohol: 5,
    taste: "甘くフルーティー",
    region: "日本全国",
    pairing: "サラダ、デザート",
    image: "/images/noimage.png",
    description: "白桃のジューシーな甘さが広がる一杯。",
    mood: "ほんのり甘い気分の時",
    year: 2023,
  },
  {
    name: "ゆずサワー",
    type: "サワー",
    alcohol: 5,
    taste: "爽やかで香り高い",
    region: "日本全国",
    pairing: "和食、焼き魚",
    image: "/images/noimage.png",
    description: "爽やかな香りと酸味が特徴。",
    mood: "気分をリフレッシュしたい時",
    year: 2023,
  },
  {
    name: "赤ワイン",
    type: "ワイン",
    alcohol: 12,
    taste: "渋みと果実味",
    region: "フランス/チリ/日本など",
    pairing: "肉料理、チーズ",
    image: "https://www.sapporobeer.jp/images/product/wine/red/redwine.png",
    description: "芳醇な香りと奥深い味わいを楽しめるワイン。",
    mood: "落ち着いて語りたい夜に",
    year: 2019,
  },
  {
    name: "白ワイン",
    type: "ワイン",
    alcohol: 12,
    taste: "さっぱり、フルーティー",
    region: "フランス/チリ/日本など",
    pairing: "魚料理、サラダ",
    image: "https://www.sapporobeer.jp/images/product/wine/white/whitewine.png",
    description: "フレッシュで爽やかな飲み口。",
    mood: "軽く楽しみたい時",
    year: 2020,
  },
  {
    name: "白鹿 純米酒",
    type: "日本酒",
    alcohol: 15,
    taste: "旨味がしっかり",
    region: "兵庫県",
    pairing: "刺身、煮物",
    image: "https://www.hakushika.co.jp/products/img/junmai_720ml.png",
    description: "米の旨味を生かした芳醇な味わい。",
    mood: "和食と共にしっぽり",
    year: 2021,
  },
  {
    name: "獺祭",
    type: "日本酒",
    alcohol: 16,
    taste: "華やかでフルーティー",
    region: "山口県",
    pairing: "寿司、チーズ",
    image: "https://www.asahishuzo.ne.jp/products/dassai45/img/product.png",
    description: "磨きぬかれた米の香りと上品な甘み。",
    mood: "特別な日の乾杯に",
    year: 2021,
  },
  {
    name: "黒霧島",
    type: "焼酎",
    alcohol: 25,
    taste: "コクと甘み",
    region: "宮崎県",
    pairing: "豚骨料理、揚げ物",
    image: "https://www.kirishima.co.jp/brands/kuromaru/img/product.png",
    description: "芋の旨味と香りが広がる本格芋焼酎。",
    mood: "しっかり飲みたい夜に",
    year: 2020,
  },
  {
    name: "二階堂",
    type: "焼酎",
    alcohol: 25,
    taste: "まろやかでクセが少ない",
    region: "大分県",
    pairing: "和食、軽いおつまみ",
    image: "https://www.nikaido-shuzo.jp/products/images/nikaido.png",
    description: "麦の香ばしさと優しい飲み口。",
    mood: "リラックスしたい時",
    year: 2020,
  },
  {
    name: "白州 ハイボール",
    type: "ハイボール",
    alcohol: 9,
    taste: "爽快でスモーキー",
    region: "山梨県",
    pairing: "燻製料理、ナッツ",
    image: "https://www.suntory.co.jp/whisky/hakushu/common/img/highball.png",
    description: "森香るウイスキーを炭酸で割った爽快な一杯。",
    mood: "自然の中でリフレッシュ",
    year: 2023,
  },
  {
    name: "バーボンハイボール",
    type: "ハイボール",
    alcohol: 10,
    taste: "甘くて力強い",
    region: "アメリカ",
    pairing: "ステーキ、バーガー",
    image:
      "https://www.suntory.co.jp/wnb/recipe/common/img/recipe/00000041.jpg",
    description: "バーボンの甘みと炭酸が合わさった飲みやすい一杯。",
    mood: "ワイルドな気分で",
    year: 2023,
  },
  {
    name: "梅酒ロック",
    type: "リキュール",
    alcohol: 12,
    taste: "甘酸っぱい・まろやか",
    region: "日本全国",
    pairing: "デザート、和食",
    image: "https://www.suntory.co.jp/wnb/umeshu/common/img/product.png",
    description: "梅の甘酸っぱさを存分に楽しめる定番酒。",
    mood: "甘い気分で癒されたい時",
    year: 2022,
  },
  {
    name: "ネグローニ",
    type: "カクテル",
    alcohol: 15,
    taste: "ビターで芳醇",
    region: "イタリア",
    pairing: "チーズ、ナッツ",
    image:
      "https://www.suntory.co.jp/wnb/recipe/common/img/recipe/00000058.jpg",
    description: "ジン・カンパリ・ベルモットを使用した大人の味わい。",
    mood: "じっくり味わう夜に",
    year: 2023,
  },
  {
    name: "アペロールスプリッツ",
    type: "カクテル",
    alcohol: 11,
    taste: "爽やかでほろ苦い",
    region: "イタリア",
    pairing: "ピザ、サラダ",
    image: "https://www.campari.jp/aperol/common/img/spritz.png",
    description: "アペロールとスパークリングワインを使った華やかなカクテル。",
    mood: "休日の午後にぴったり",
    year: 2023,
  },
  {
    name: "マルガリータ",
    type: "カクテル",
    alcohol: 15,
    taste: "酸味と塩気のバランス",
    region: "メキシコ",
    pairing: "タコス、メキシカン料理",
    image:
      "https://www.suntory.co.jp/wnb/recipe/common/img/recipe/00000060.jpg",
    description: "テキーラをベースにライムと塩で仕上げたカクテル。",
    mood: "陽気な気分で楽しみたい時",
    year: 2023,
  },
  {
    name: "IPA クラフトビール",
    type: "クラフトビール",
    alcohol: 7,
    taste: "ホップの苦味と香り",
    region: "アメリカ/日本",
    pairing: "肉料理、ピザ",
    image: "https://www.sapporobeer.jp/images/product/craft/ipa/ipa.png",
    description: "クラフトビールならではのホップの香りが楽しめる。",
    mood: "個性的な味を楽しみたい時",
    year: 2023,
  },
  {
    name: "ヘーフェヴァイツェン",
    type: "クラフトビール",
    alcohol: 5,
    taste: "フルーティーで軽やか",
    region: "ドイツ",
    pairing: "ソーセージ、サラダ",
    image: "https://www.sapporobeer.jp/images/product/craft/weizen/weizen.png",
    description: "バナナのような香りが特徴の小麦ビール。",
    mood: "ゆったり休日に",
    year: 2023,
  },
  {
    name: "スパークリングワイン",
    type: "ワイン",
    alcohol: 12,
    taste: "爽快な泡立ち",
    region: "フランス/イタリア/日本など",
    pairing: "オードブル、デザート",
    image:
      "https://www.sapporobeer.jp/images/product/wine/sparkling/sparkling.png",
    description: "華やかな泡立ちと爽快感が魅力のワイン。",
    mood: "お祝いの乾杯に",
    year: 2023,
  },
];
